db:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  # volumes:
  #   - docker-example-postgres:/var/lib/postgresql/data

app:
  # use the Dockerfile next to this file
  build: .

  # sources environment variable configuration for our app
  env_file: .env

  # rely on the RAILS_ENV value of the host machine
  environment:
    RAILS_ENV: development

  # makes the app container aware of the DB container
  links:
    - db:db.local

  # expose the port we configured Unicorn to bind to
  expose:
    - "3000"

# service configuration for our web server
web:

  # set the build context to the root of the Rails app
  build: .

  # build with a different Dockerfile
  dockerfile: config/containers/Dockerfile-nginx

  # makes the web container aware of the app container
  links:
    - db

  # expose the port we configured Nginx to bind to
  ports:
    - "50:50"